global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: netconf-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:5000

